movie_genres = {
    "Cloudy With A Chance Of Meatballs": "Animation,Comedy",
    "None": "Unknown",
    "Action Movie": "Action",
    "Mamma Mia": "Musical,Comedy",
    "Dragon": "Animation",
    "Rick And Morty": "Animation,Comedy",
    "Home Alone": "Comedy,Family",
    "The Big Lebowski": "Comedy,Crime",
    "Spider-Man": "Superhero,Action",
    "Goodfellas": "Crime,Drama",
    "Dead Silence": "Horror,Thriller",
    "La La Land": "Musical,Drama,Romance",
    "Harry Potter": "Fantasy,Adventure",
    "Transformer": "Action,Sci-Fi",
    "Teenage Mutant Ninja Turtles": "Animation,Action",
    "High School Musical": "Musical,Comedy,Family",
    "Despicable Me": "Animation,Comedy",
    "Toy Story": "Animation,Adventure",
    "The Godfather": "Crime,Drama",
    "Fast And Furious": "Action,Thriller",
    "The Garfield Movie": "Animation,Comedy",
    "Ratatouille": "Animation,Comedy",
    "Five Nights At Freddies": "Horror",
    "Back To The Future": "Sci-Fi,Adventure",
    "Mystic Pizza": "Comedy,Drama,Romance",
    "Iron Man": "Superhero,Action",
    "Life Of Pi": "Adventure,Drama",
    "Avengers": "Superhero,Action",
    "King Kong": "Action,Adventure,Drama",
    "Whiplash": "Drama,Music",
    "Inside Out": "Animation,Drama",
    "Superbad": "Comedy",
    "Stranger Things": "Sci-Fi,Horror,Drama",
    "Air Bud": "Family,Comedy",
    "Deadpool": "Action,Comedy",
    "A Quiet Place": "Horror,Thriller",
    "Finding Nemo": "Animation,Adventure",
    "My Cousin Vinny": "Comedy,Crime",
    "Eat Pray Love": "Drama,Romance",
    "Pulp Fiction": "Crime,Thriller",
    "Star Wars": "Sci-Fi,Adventure",
    "Batman": "Superhero,Action",
    "Shrek": "Animation,Comedy",
    "Scooby Doo": "Animation,Adventure",
    "Princess Diaries": "Comedy,Family,Romance",
    "Wall-E": "Animation,Sci-Fi",
    "The Hangover": "Comedy",
    "Breaking Bad": "Crime,Drama",
    "Interstellar": "Sci-Fi,Adventure,Drama",
    "Rush Hour": "Action,Comedy",
    "The Truman Show": "Drama,Sci-Fi",
    "Futurama": "Animation,Comedy,Sci-Fi",
    "Godfather": "Crime,Drama",
    "The Dictator": "Comedy,Political",
    "Borat": "Comedy,Political",
    "Mission: Impossible": "Action,Thriller",
    "Avengers: Endgame": "Superhero,Action",
    "Titanic": "Drama,Romance",
    "Dangal": "Drama,Sports",
    "Kung Fu Panda": "Animation,Action",
    "The Mummy": "Action,Adventure",
    "The Invisible Guest": "Thriller,Mystery",
    "Squid Game": "Drama,Thriller",
    "Parasite": "Thriller,Drama",
    "Blade Runner": "Sci-Fi,Thriller",
    "Spider-Man: Into The Spider-Verse": "Animation,Action",
    "Everything Everywhere All At Once": "Sci-Fi,Action,Adventure",
    "Barbie": "Comedy,Family",
    "Jurassic Park": "Adventure,Sci-Fi",
    "Ponyo": "Animation,Fantasy",
    "My Neighbor Totoro": "Animation,Family",
    "Kill Bill": "Action,Thriller",
    "Jiro Dreams Of Sushi": "Documentary",
    "Naruto": "Animation,Action",
    "Frozen": "Animation,Adventure,Family",
    "Shawshank Redemption": "Drama",
    "Mad Max": "Action,Sci-Fi",
    "The Lion King": "Animation,Adventure,Drama",
    "Your Name": "Animation,Romance,Fantasy",
    "Memoirs Of A Geisha": "Drama,Romance",
    "Godzilla": "Action,Sci-Fi",
    "Shazam": "Superhero,Action",
    "The Grinch": "Animation,Comedy,Family",
    "Zootopia": "Animation,Adventure,Comedy",
    "The Godfather Part II": "Crime,Drama",
    "The Social Network": "Drama",
    "The Big Sick": "Comedy,Drama,Romance",
    "Die Hard": "Action,Thriller",
    "Taxi Driver": "Crime,Drama,Thriller",
    "Fast & Furious": "Action,Thriller",
    "The Karate Kid": "Drama,Family",
    "John Wick": "Action,Thriller",
    "Bladerunner": "Sci-Fi,Thriller",
    "Parasite": "Thriller,Drama",
    "Gone Girl": "Thriller,Drama",
    "Inception": "Sci-Fi,Thriller",
    "The Breakfast Club": "Comedy,Drama",
    "The Lego Movie": "Animation,Adventure,Comedy",
    "Spider-Man: Far From Home": "Superhero,Action",
    "Space Jam": "Animation,Comedy",
    "Spongebob": "Animation,Comedy",
    "Toy Story 4": "Animation,Adventure",
    "Green Book": "Drama",
    "Madagascar": "Animation,Adventure,Comedy",
    "The Mario Movie": "Animation,Adventure",
    "The Big Lebowski": "Comedy,Crime",
    "The Road To Fallujah": "Documentary",
    "Kingdom Of Heaven": "Action,Adventure,Drama",
    "The Dictator": "Comedy,Political",
    "Rush Hour": "Action,Comedy",
    "Breaking Bad": "Crime,Drama",
    "The Boys": "Superhero,Action",
    "Wicked": "Musical,Fantasy",
    "Eternal Sunshine Of The Spotless Mind": "Drama,Romance,Sci-Fi",
    "The Grinch": "Animation,Comedy,Family",
    "Ratatouille": "Animation,Comedy",
    "Star Wars: The Last Jedi": "Sci-Fi,Action",
    "The Dictator": "Comedy",
    "The Lego Movie 2": "Animation,Comedy,Adventure",
    "Dune": "Sci-Fi,Adventure"
}